### ISSUE TITLE
Typo in the description

### ISSUE THREAD

**Issue by maxdeleoni** [tommasobonomo/covid19-italy#13]
There is a typo in the description of exponential growth: "where cases_n stands for the number of cases registered on day n", because "number of cases" can be easily interpreted as "on the specific day, only".
With this misinterpretation at hand, it would look like that the absolute number of positive cases is still getting larger and larger, which is not always the case. 

I assume that the sentence should be replaced with something along the line: "where cases_n stands for the number of cases registered UP TO day n", or - less preferable - "where cases_n stands for the TOTAL number of cases registered on day n"(implying "total number of cases" means "since the beginning").

**Comment by tommasobonomo** [comment]
Thank you for your comment, I agree that the description could be misleading! I will tweak it with the next feature release :)
